steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-python312-app:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-python312-app:latest']

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud run deploy fastapi-python312-app \
        --image gcr.io/$PROJECT_ID/fastapi-python312-app:latest \
        --platform managed \
        --region us-west2 \
        --allow-unauthenticated

  # Step 4: Update the environment variable using the canonical service URL directly
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud run services update fastapi-python312-app \
        --platform managed \
        --region us-west2 \
        --update-env-vars BASE_URL=$(gcloud run services describe fastapi-python312-app --platform managed --region us-west2 --format="value(metadata.annotations['run.googleapis.com/urls'])" | sed 's/\[//g' | sed 's/\]//g' | cut -d ',' -f 1 | sed 's/"//g')

images:
- 'gcr.io/$PROJECT_ID/fastapi-python312-app:latest'
